# generated
name: x_3xgovsvg5vyscvtg
on:
  workflow_dispatch:
    inputs:
      x_jnhp7mnt7b3mb5hb:
        type: string
        required: true
  workflow_call:
    inputs:
      x_jnhp7mnt7b3mb5hb:
        type: string
        required: true
permissions: {}
jobs:
  x_kqfbge5rdw2i6lyt:
    name: x_kqfbge5rdw2i6lyt
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      contents: read
      id-token: write
    outputs:
      x_ehwa7slqd33gurxq: ${{ steps.run.outputs.x_ehwa7slqd33gurxq }}
      x_gamddzghb65dclbw: ${{ steps.run.outputs.x_gamddzghb65dclbw }}
      x_lgxugsfjen7buvvx: ${{ steps.run.outputs.x_lgxugsfjen7buvvx }}
      x_wa6vjgjotlgujoxk: ${{ steps.run.outputs.x_wa6vjgjotlgujoxk }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          x_i6ds74vrj7i57xsa: ${{ secrets.x_z22rj5ks4pfo3ccd }}
          x_4qj3lf5256ldlwqi: ${{ secrets.x_ticopka5jd577quy }}
          x_nlzyq6tbjh3sbclz: ${{ secrets.x_o37k35rc5ffoofol }}
          x_5ixbtnxm5is2lic3: x_juhk5phmg6yxcuql
          x_ouhzvxals3nqz3rv: x_ehwa7slqd33gurxq,x_gamddzghb65dclbw,x_lgxugsfjen7buvvx,x_wa6vjgjotlgujoxk
          x_jnhp7mnt7b3mb5hb: ${{ inputs.x_jnhp7mnt7b3mb5hb }}
          x_qhupe5pa4pxgu4x6: ${{ secrets.x_7rsgk3kvytpobykp }}
          x_brggqxen6lr3apsr: ${{ secrets.x_hjypnf4up5o35lhq }}
          x_n25keoftnlex5xds: ${{ secrets.x_pmwydb7d4ke7lx5j }}
          x_pwg2psg5ia7nlwcm: ${{ secrets.x_lkztj3rtrsymdchb }}
        run: ./.github/bin/x_3xgovsvg5vyscvtg
  x_nzto5zhpmksb6vuj:
    name: x_nzto5zhpmksb6vuj
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      contents: read
      id-token: write
    needs:
      - x_kqfbge5rdw2i6lyt
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          x_i6ds74vrj7i57xsa: ${{ secrets.x_z22rj5ks4pfo3ccd }}
          x_4qj3lf5256ldlwqi: ${{ secrets.x_ticopka5jd577quy }}
          x_nlzyq6tbjh3sbclz: ${{ secrets.x_o37k35rc5ffoofol }}
          x_5ixbtnxm5is2lic3: x_sqhzwn2ueeupc3wa
          x_ouhzvxals3nqz3rv: ''
          x_ot5mkbqfqhhqlppf: ${{ needs.x_kqfbge5rdw2i6lyt.outputs.x_wa6vjgjotlgujoxk }}
          x_cybcsoumqt77f57p: ${{ secrets.x_lrdr7qzxxyi7wyrc }}
          x_3uoumauqseukuclg: ${{ secrets.x_v54akbnuaw2kddjx }}
          x_qhupe5pa4pxgu4x6: ${{ secrets.x_7rsgk3kvytpobykp }}
          x_brggqxen6lr3apsr: ${{ secrets.x_hjypnf4up5o35lhq }}
          x_n25keoftnlex5xds: ${{ secrets.x_pmwydb7d4ke7lx5j }}
          x_lujcxrkcr363cub7: ${{ secrets.x_42v7e3uwkibbgwhg }}
          x_na4ie3kheya5xgax: ${{ secrets.x_avzqcnkweqdfst5z }}
          x_u36ojmluqirzee6c: ${{ secrets.x_ur4musmvja6wylwn }}
          x_pwg2psg5ia7nlwcm: ${{ secrets.x_lkztj3rtrsymdchb }}
          x_3qqyq7q4qcztxtgg: ${{ secrets.x_vw62xczewgexx6n7 }}
          x_hdys4cb5r3lycb4c: ${{ secrets.x_5pp3o7szrq62i3y4 }}
        run: ./.github/bin/x_3xgovsvg5vyscvtg
  x_utqdzdjo2i3ckodk:
    name: x_utqdzdjo2i3ckodk
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      contents: read
      id-token: write
    needs:
      - x_kqfbge5rdw2i6lyt
    outputs:
      x_qnkmglwukb2kvwve: ${{ steps.run.outputs.x_qnkmglwukb2kvwve }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          x_i6ds74vrj7i57xsa: ${{ secrets.x_z22rj5ks4pfo3ccd }}
          x_4qj3lf5256ldlwqi: ${{ secrets.x_ticopka5jd577quy }}
          x_nlzyq6tbjh3sbclz: ${{ secrets.x_o37k35rc5ffoofol }}
          x_5ixbtnxm5is2lic3: x_4uz4actg6f3oxf7f
          x_ouhzvxals3nqz3rv: x_qnkmglwukb2kvwve
          x_3altuwzgbpt2zuey: ${{ needs.x_kqfbge5rdw2i6lyt.outputs.x_wa6vjgjotlgujoxk }}
          x_cybcsoumqt77f57p: ${{ secrets.x_lrdr7qzxxyi7wyrc }}
          x_3uoumauqseukuclg: ${{ secrets.x_v54akbnuaw2kddjx }}
          x_qhupe5pa4pxgu4x6: ${{ secrets.x_7rsgk3kvytpobykp }}
          x_brggqxen6lr3apsr: ${{ secrets.x_hjypnf4up5o35lhq }}
          x_n25keoftnlex5xds: ${{ secrets.x_pmwydb7d4ke7lx5j }}
          x_pwg2psg5ia7nlwcm: ${{ secrets.x_lkztj3rtrsymdchb }}
        run: ./.github/bin/x_3xgovsvg5vyscvtg
  x_wrkh3mmnkvjpgdxl:
    name: x_wrkh3mmnkvjpgdxl
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      contents: read
      id-token: write
    needs:
      - x_kqfbge5rdw2i6lyt
      - x_nzto5zhpmksb6vuj
      - x_utqdzdjo2i3ckodk
    strategy:
      fail-fast: false
      matrix:
        x_q3zzs54jkxapqhkz: ${{ fromJSON(needs.x_utqdzdjo2i3ckodk.outputs.x_qnkmglwukb2kvwve) }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          x_i6ds74vrj7i57xsa: ${{ secrets.x_z22rj5ks4pfo3ccd }}
          x_4qj3lf5256ldlwqi: ${{ secrets.x_ticopka5jd577quy }}
          x_nlzyq6tbjh3sbclz: ${{ secrets.x_o37k35rc5ffoofol }}
          x_5ixbtnxm5is2lic3: x_snwd547jjr2p6usp
          x_ouhzvxals3nqz3rv: ''
          x_2pjlwoyyprv6nof5: ${{ needs.x_kqfbge5rdw2i6lyt.outputs.x_wa6vjgjotlgujoxk }}
          x_4vemsucmreh53tpf: ${{ needs.x_kqfbge5rdw2i6lyt.outputs.x_ehwa7slqd33gurxq }}
          x_aojwkimzfpto7f2h: ${{ matrix.x_q3zzs54jkxapqhkz }}
          x_umpsxxwps75zk64j: ${{ needs.x_kqfbge5rdw2i6lyt.outputs.x_gamddzghb65dclbw }}
          x_xtvb6t67fgiblcrv: ${{ needs.x_kqfbge5rdw2i6lyt.outputs.x_lgxugsfjen7buvvx }}
          x_cybcsoumqt77f57p: ${{ secrets.x_lrdr7qzxxyi7wyrc }}
          x_3uoumauqseukuclg: ${{ secrets.x_v54akbnuaw2kddjx }}
          x_qhupe5pa4pxgu4x6: ${{ secrets.x_7rsgk3kvytpobykp }}
          x_brggqxen6lr3apsr: ${{ secrets.x_hjypnf4up5o35lhq }}
          x_n25keoftnlex5xds: ${{ secrets.x_pmwydb7d4ke7lx5j }}
          x_lujcxrkcr363cub7: ${{ secrets.x_42v7e3uwkibbgwhg }}
          x_na4ie3kheya5xgax: ${{ secrets.x_avzqcnkweqdfst5z }}
          x_u36ojmluqirzee6c: ${{ secrets.x_ur4musmvja6wylwn }}
          x_pwg2psg5ia7nlwcm: ${{ secrets.x_lkztj3rtrsymdchb }}
          x_3qqyq7q4qcztxtgg: ${{ secrets.x_vw62xczewgexx6n7 }}
          x_hdys4cb5r3lycb4c: ${{ secrets.x_5pp3o7szrq62i3y4 }}
        run: ./.github/bin/x_3xgovsvg5vyscvtg
  x_hqhkrnunos6pgvus:
    name: x_hqhkrnunos6pgvus
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      contents: read
      id-token: write
    needs:
      - x_kqfbge5rdw2i6lyt
      - x_nzto5zhpmksb6vuj
      - x_wrkh3mmnkvjpgdxl
    if: ${{ always() }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          x_i6ds74vrj7i57xsa: ${{ secrets.x_z22rj5ks4pfo3ccd }}
          x_4qj3lf5256ldlwqi: ${{ secrets.x_ticopka5jd577quy }}
          x_nlzyq6tbjh3sbclz: ${{ secrets.x_o37k35rc5ffoofol }}
          x_5ixbtnxm5is2lic3: x_ji5cdzhsn7xxkfum
          x_ouhzvxals3nqz3rv: ''
          x_fuow2euxip6xradr: ${{ needs.x_kqfbge5rdw2i6lyt.outputs.x_wa6vjgjotlgujoxk }}
          x_gwwyooyr6h7xcjm3: ${{ needs.x_wrkh3mmnkvjpgdxl.result }}
          x_patmclywolfvc7hw: ${{ needs.x_nzto5zhpmksb6vuj.result }}
          x_cybcsoumqt77f57p: ${{ secrets.x_lrdr7qzxxyi7wyrc }}
          x_3uoumauqseukuclg: ${{ secrets.x_v54akbnuaw2kddjx }}
          x_qhupe5pa4pxgu4x6: ${{ secrets.x_7rsgk3kvytpobykp }}
          x_brggqxen6lr3apsr: ${{ secrets.x_hjypnf4up5o35lhq }}
          x_n25keoftnlex5xds: ${{ secrets.x_pmwydb7d4ke7lx5j }}
          x_lujcxrkcr363cub7: ${{ secrets.x_42v7e3uwkibbgwhg }}
          x_na4ie3kheya5xgax: ${{ secrets.x_avzqcnkweqdfst5z }}
          x_u36ojmluqirzee6c: ${{ secrets.x_ur4musmvja6wylwn }}
          x_pwg2psg5ia7nlwcm: ${{ secrets.x_lkztj3rtrsymdchb }}
          x_3qqyq7q4qcztxtgg: ${{ secrets.x_vw62xczewgexx6n7 }}
          x_hdys4cb5r3lycb4c: ${{ secrets.x_5pp3o7szrq62i3y4 }}
        run: ./.github/bin/x_3xgovsvg5vyscvtg
