# generated
name: x_par546kosx6fiems
on:
  workflow_dispatch:
    inputs:
      x_56dxuqyaddjt6jup:
        type: string
        required: true
  workflow_call:
    inputs:
      x_56dxuqyaddjt6jup:
        type: string
        required: true
permissions: {}
jobs:
  x_v7rw7i6omev2hofu:
    name: x_v7rw7i6omev2hofu
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      contents: read
      id-token: write
    outputs:
      x_6ses4e7s6pb262ks: ${{ steps.run.outputs.x_6ses4e7s6pb262ks }}
      x_ccmrhakdap5obgxr: ${{ steps.run.outputs.x_ccmrhakdap5obgxr }}
      x_exzmsuizolvao4go: ${{ steps.run.outputs.x_exzmsuizolvao4go }}
      x_pv5fjz5hxyniwun6: ${{ steps.run.outputs.x_pv5fjz5hxyniwun6 }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          x_ql4m25b7g2m6tntv: ${{ secrets.x_a66xgm4io6ezvxqy }}
          x_kkmzipjlialhp7e2: ${{ secrets.x_fsabwi4ev574rtnd }}
          x_lieanakfu5brycoz: ${{ secrets.x_ie4jwj4msp4iusg2 }}
          x_cuycqk6gd7bglgfd: x_f76dalwt6k3agccr
          x_yef7je2yu6bqkh4r: x_6ses4e7s6pb262ks,x_ccmrhakdap5obgxr,x_exzmsuizolvao4go,x_pv5fjz5hxyniwun6
          x_56dxuqyaddjt6jup: ${{ inputs.x_56dxuqyaddjt6jup }}
          x_c56fvcpivwzgsjx7: ${{ secrets.x_hp3e5lq3tmbm33ly }}
          x_js64rxpyeihzwrzc: ${{ secrets.x_hx5msrd72lljmxse }}
          x_4aacycgonccy5cua: ${{ secrets.x_ffxarh34x32tsxdh }}
          x_malwdxffvdeomxnx: ${{ secrets.x_dfrlp4tguapwovad }}
        run: ./.github/bin/x_par546kosx6fiems
  x_64vlsapbbaiznn6g:
    name: x_64vlsapbbaiznn6g
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      contents: read
      id-token: write
    needs:
      - x_v7rw7i6omev2hofu
    outputs:
      x_dhfqg7y7ktkdubqy: ${{ steps.run.outputs.x_dhfqg7y7ktkdubqy }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          x_ql4m25b7g2m6tntv: ${{ secrets.x_a66xgm4io6ezvxqy }}
          x_kkmzipjlialhp7e2: ${{ secrets.x_fsabwi4ev574rtnd }}
          x_lieanakfu5brycoz: ${{ secrets.x_ie4jwj4msp4iusg2 }}
          x_cuycqk6gd7bglgfd: x_efe7n74pur7fcoq7
          x_yef7je2yu6bqkh4r: x_dhfqg7y7ktkdubqy
          x_nbedteiln6lfqown: ${{ needs.x_v7rw7i6omev2hofu.outputs.x_exzmsuizolvao4go }}
          x_n2otbpmtx2gz4tqp: ${{ secrets.x_rjrxyi5zwyig57lu }}
          x_2xn3pa7wjrzsgecf: ${{ secrets.x_nvdlaicdppwinsmu }}
          x_c56fvcpivwzgsjx7: ${{ secrets.x_hp3e5lq3tmbm33ly }}
          x_js64rxpyeihzwrzc: ${{ secrets.x_hx5msrd72lljmxse }}
          x_4aacycgonccy5cua: ${{ secrets.x_ffxarh34x32tsxdh }}
          x_malwdxffvdeomxnx: ${{ secrets.x_dfrlp4tguapwovad }}
        run: ./.github/bin/x_par546kosx6fiems
  x_ippvh5h5ro5oqy7s:
    name: x_ippvh5h5ro5oqy7s
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      contents: read
      id-token: write
    needs:
      - x_v7rw7i6omev2hofu
      - x_64vlsapbbaiznn6g
    strategy:
      fail-fast: false
      matrix:
        x_pa27dz4x53qhcgd2: ${{ fromJSON(needs.x_64vlsapbbaiznn6g.outputs.x_dhfqg7y7ktkdubqy) }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          x_ql4m25b7g2m6tntv: ${{ secrets.x_a66xgm4io6ezvxqy }}
          x_kkmzipjlialhp7e2: ${{ secrets.x_fsabwi4ev574rtnd }}
          x_lieanakfu5brycoz: ${{ secrets.x_ie4jwj4msp4iusg2 }}
          x_cuycqk6gd7bglgfd: x_oapqdtkzgxzr6ldb
          x_yef7je2yu6bqkh4r: ''
          x_vvgij6tivcga57r7: ${{ needs.x_v7rw7i6omev2hofu.outputs.x_pv5fjz5hxyniwun6 }}
          x_wpqpmt5gmz5cu4xc: ${{ matrix.x_pa27dz4x53qhcgd2 }}
          x_wsqxlsurmlj6yyzn: ${{ needs.x_v7rw7i6omev2hofu.outputs.x_ccmrhakdap5obgxr }}
          x_z37q3tcgcrxd7z36: ${{ needs.x_v7rw7i6omev2hofu.outputs.x_6ses4e7s6pb262ks }}
          x_zb4wxn64tcosmyyv: ${{ needs.x_v7rw7i6omev2hofu.outputs.x_exzmsuizolvao4go }}
          x_n2otbpmtx2gz4tqp: ${{ secrets.x_rjrxyi5zwyig57lu }}
          x_2xn3pa7wjrzsgecf: ${{ secrets.x_nvdlaicdppwinsmu }}
          x_rla2jtz7kws4urz6: ${{ secrets.x_dmyiwdqxsnmwnvpf }}
          x_c56fvcpivwzgsjx7: ${{ secrets.x_hp3e5lq3tmbm33ly }}
          x_js64rxpyeihzwrzc: ${{ secrets.x_hx5msrd72lljmxse }}
          x_4aacycgonccy5cua: ${{ secrets.x_ffxarh34x32tsxdh }}
          x_dggxci6w7bnds2qe: ${{ secrets.x_vrsoq675r6izel3q }}
          x_gntfsn2itjfeukf7: ${{ secrets.x_vlst3telc6yi6xcs }}
          x_tcfqycxbahmdnzet: ${{ secrets.x_wzpchvsfjp3svnqf }}
          x_malwdxffvdeomxnx: ${{ secrets.x_dfrlp4tguapwovad }}
          x_dqq6e5bg556xrhyv: ${{ secrets.x_qyv3mmev75ytrro7 }}
          x_niadrjptwouvwc3g: ${{ secrets.x_yohyjlzs47mg2mus }}
          x_rcaatwspy4kbpmty: ${{ secrets.x_oyuq77qvikwvicfv }}
        run: ./.github/bin/x_par546kosx6fiems
  x_la5vscwxq2uwycww:
    name: x_la5vscwxq2uwycww
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      contents: read
      id-token: write
    needs:
      - x_ippvh5h5ro5oqy7s
    if: ${{ always() }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          x_ql4m25b7g2m6tntv: ${{ secrets.x_a66xgm4io6ezvxqy }}
          x_kkmzipjlialhp7e2: ${{ secrets.x_fsabwi4ev574rtnd }}
          x_lieanakfu5brycoz: ${{ secrets.x_ie4jwj4msp4iusg2 }}
          x_cuycqk6gd7bglgfd: x_msihvpnvezs4hhbd
          x_yef7je2yu6bqkh4r: ''
          x_7qn26fqgs6vogvnm: ${{ needs.x_ippvh5h5ro5oqy7s.result }}
          x_c56fvcpivwzgsjx7: ${{ secrets.x_hp3e5lq3tmbm33ly }}
          x_js64rxpyeihzwrzc: ${{ secrets.x_hx5msrd72lljmxse }}
          x_4aacycgonccy5cua: ${{ secrets.x_ffxarh34x32tsxdh }}
          x_malwdxffvdeomxnx: ${{ secrets.x_dfrlp4tguapwovad }}
        run: ./.github/bin/x_par546kosx6fiems
